# Generated by Django 4.2.1 on 2023-05-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scribbleuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already in use.'}, max_length=254, unique=True),
        ),
    ]
