# Generated by Django 4.2.1 on 2023-05-14 12:59

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_scribbleuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scribbleuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 28 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=28, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
