# Generated by Django 4.2.1 on 2023-05-14 13:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28)),
                ('author', models.CharField(max_length=28)),
                ('content', models.TextField(max_length=2000)),
                ('flames', models.IntegerField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), max_length=5, size=None)),
            ],
        ),
    ]
