# Generated by Django 4.2.1 on 2023-05-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags_string',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
