# Generated by Django 4.2.1 on 2023-05-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_tags_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_type',
            field=models.CharField(choices=[('poem', 'Poem'), ('story', 'Story'), ('paper', 'Paper')], default='story', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='posts.tag'),
        ),
    ]
