# Generated by Django 4.2.1 on 2023-05-14 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_alter_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='flames',
        ),
        migrations.AddField(
            model_name='post',
            name='flames',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
