# Generated by Django 4.2.1 on 2023-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='posts.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags_string',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
