# Generated by Django 4.2.1 on 2023-05-28 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0012_alter_post_tags_alter_post_tags_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('plagiarism', 'Plagiarism'), ('dangerous', 'Dangerous'), ('offensive', 'Offensive'), ('hate_speech', 'Hate Speech'), ('nsfw', 'Nsfw'), ('illegal', 'Illegal'), ('other', 'Other')], default='', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('important', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
