# Generated by Django 4.2.1 on 2023-05-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_postreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
