# Generated by Django 4.2.1 on 2023-05-28 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_postreport_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.CharField(choices=[('plagiarism', 'Plagiarism'), ('dangerous', 'Dangerous'), ('offensive', 'Offensive'), ('hate_speech', 'Hate Speech'), ('nsfw', 'Nsfw'), ('illegal', 'Illegal'), ('other', 'Other')], default='dangerous', max_length=30),
        ),
    ]
