# Generated by Django 4.2.1 on 2023-05-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_author_alter_postreport_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=28),
        ),
    ]
